### ISSUE TITLE
zopfli.pngcompress is not a function

### ISSUE THREAD

**Issue by MatTheCat** [jaeh/node-zopfli-es#2]
Using v1.0.1 calling `zopflipng` fails with the following output:

```
node_modules/node-zopfli-es/bin/zopflipng.js:54
  zopfli.pngcompress(program.args[0], program.args[1], options)
         ^

TypeError: zopfli.pngcompress is not a function
    at Object.<anonymous> (node_modules/node-zopfli-es/bin/zopflipng.js:54:10)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)
```

**Comment by jaeh** [comment]
when i tried to readd zopfli.pngcompress, it threw an error.
guess it happened after i updated zopfli, will try to look at that soon.

**Comment by MatTheCat** [comment]
After looking at [zopfli.js](https://github.com/jaeh/node-zopfli-es/blob/master/lib/zopfli.js) history it seems `pngcompress` never existed. Is it planned to implement it?

**Comment by jaeh** [comment]
sorry for the late answer.

there are no new features planned, but i would love to accept a pull request.

this library is also now frozen and will receive security fixes, but no other changes.

in the next 3 months, before september 2020, i will port the library to ecmascript modules and maybe will add this functionality there:

https://github.com/magic/zopfli.
